#!/usr/bin/env python

__author__ = "Marco Galardini"
__version__ = '0.1.0'

def get_options():
    import argparse

    # create the top-level parser
    description = "Extract adapters sequences from a FastQC report"
    parser = argparse.ArgumentParser(description = description,
                                     prog = 'fastqc_adapters')

    parser.add_argument('fastqc', action='store',
                        help='FastQC report')

    parser.add_argument('--version', action='version',
                         version='%(prog)s '+__version__)

    return parser.parse_args()

if __name__ == "__main__":
    options = get_options()

    b = False
    for l in open(options.fastqc):
        if '>>Overrepresented sequences' in l:
            b = True
            continue
        if not b:
            continue
        if l.strip().startswith('#Sequence'):
            continue
        elif l.strip().startswith('>>END_MODULE'):
            break

        print(l.strip().split()[0])
