#!/usr/bin/env python

__author__ = "Marco Galardini"
__version__ = '0.1.0'

def get_options():
    import argparse

    # create the top-level parser
    description = "Convert a GenBank file to Fasta"
    parser = argparse.ArgumentParser(description = description,
                                     prog = 'gbk2fasta')

    parser.add_argument('gbk', action='store',
                        help='GenBank file')
    parser.add_argument('fasta', action='store',
                        help='Fasta file')

    parser.add_argument('--version', action='version',
                         version='%(prog)s '+__version__)

    return parser.parse_args()

if __name__ == "__main__":
    options = get_options()

    from Bio import SeqIO

    SeqIO.write(SeqIO.parse(options.gbk, 'genbank'),
                options.fasta, 'fasta')
