#!/usr/bin/env python

__author__ = "Marco Galardini"
__version__ = '0.1.0'

def get_options():
    import argparse

    # create the top-level parser
    description = ("Get statistics from the transcriptome analysis\n" +
                  "The program expects a stdin stream of the unmapped reads.")
    parser = argparse.ArgumentParser(description = description,
                                     prog = 'get_stats')

    parser.add_argument('name', action='store',
                        help='Strain name')
    parser.add_argument('forward', action='store',
                        help='Forward BAM file')
    parser.add_argument('reverse', action='store',
                        help='Reverse BAM file')

    parser.add_argument('--version', action='version',
                         version='%(prog)s '+__version__)

    return parser.parse_args()

if __name__ == "__main__":
    options = get_options()

    import sys
    import pysam
    from Bio import SeqIO

    fmapped = reduce(lambda x, y: x + y,
            [ int(l.rstrip('\n').split('\t')[2])
                for l in pysam.idxstats(options.forward) ])
    rmapped = reduce(lambda x, y: x + y,
            [ int(l.rstrip('\n').split('\t')[2])
                for l in pysam.idxstats(options.reverse) ])

    unmapped = reduce(lambda x, y: x + y,
            [1 for x in SeqIO.parse(sys.stdin, 'fastq')])

    print('#name\ttotal\tforward\treverse\tunmapped')
    print('\t'.join([str(x) for x in [options.name,
                                      fmapped+rmapped+unmapped,
                                      fmapped,
                                      rmapped,
                                      unmapped]]))
