#!/usr/bin/env python


__author__ = "Marco Galardini"
__version__ = "0.0.1"

def get_options():
    import argparse

    # create the top-level parser
    description = "Extract ribosomial transcripts from a genbank file"
    parser = argparse.ArgumentParser(description = description,
                                     prog = 'gff2ribosomial')
    parser.add_argument('ingff', action='store',
                        help='Input GFF file')

    parser.add_argument('--version', action='version',
                         version='%(prog)s '+__version__)

    return parser.parse_args()

if __name__ == "__main__":
    from BCBio import GFF
    import sys
    options = get_options()

    # Read the input gbk
    unnamed = 1
    for s in GFF.parse(options.ingff):
        for f in s.features:
            if f.type not in set(('CDS', 'rRNA', 'tRNA')):
                continue
            if f.type == 'CDS':
                if 'GO_function' in f.qualifiers:
                    if len([x for x in f.qualifiers['GO_function']
                            if 'GO:0003735' in x]) == 0:
                        continue
                else:
                    continue
            # Name
            # Try first with the locus_tag
            try:
                name = f.qualifiers['locus_tag'][0]
            except:
                name = 'unnamed_%d' % unnamed
                unnamed += 1

            # Sequence
            seq = str(f.extract(s).seq)

            print('>%s\n%s' % (name, seq))
