#!/usr/bin/env python

def get_options():
    import argparse

    description = 'Remove some samples from the samples table'
    parser = argparse.ArgumentParser(description=description,
                                     prog='purge_sample_table')

    parser.add_argument('table', action='store',
                        help='Samples table')
    parser.add_argument('discard', action='store',
                        help='Samples to be discarded')
    
    parser.add_argument('--reference', action='append',
        default=[],
        help='Strain to be used to add the "reference" column [Default: don\'t add this column]')

    return parser.parse_args()

if __name__ == "__main__":
    options = get_options()

    import sys
    import pandas as pd

    t = pd.read_table(options.table, sep=' ').set_index('sample')
    t.drop([x.rstrip()
            for x in open(options.discard)
            if x.rstrip() in t.index],
           inplace=True)
    if len(options.reference) != 0:
        t['reference'] = [True if x in options.reference
                          else False
                          for x in t['strain']]
        t['mstrain'] = ['reference' if x in options.reference
                        else x
                        for x in t['strain']]
    t.reset_index().to_csv(sys.stdout, sep='\t', index=False)
